t:_5e8%#i:!#v:^n:5000
\tt Si
\tt Mi
\tt Sv
\tt vv
\tt 1_i
\t5?t %v
\t10?t Ev
\t10?t Rv
\t10?t Zv
\t10?t ii
v:@m:!n,n:256
t:_5e8%nnn
\tt mm
\ttn mv
\ttn vm
\ttn mSm
v:,s:5
t:100000
\tt 2*1+3*s++4
\tt 2*1+3*v++4
\\

L12345(4 8 16 32 64) ?^(70-1000) byte(7) sync(50?) gpu(20000) ssd(100000)
L2(104/../300)L3(52/104/200)L4(26/52)

[jv]s'(join value split)
x !wi x_:i:@<xS'Zx:='w@\x  12972[2315]
\tt o*x
\tt n.x
\t5?t +\i
\t5?t ?i
\t5?t =i
\t10?t ^i
\t50?t ^e
x:1'`kj
\t23 ?x
\t23 =x


